### ISSUE TITLE
'dev' branch?

### ISSUE THREAD

**Issue by karlicoss** [pawelad/pymonzo#30]
Hi, just noticed there is a dev branch, that seems more up to date with main. Just wondering if you're ever planning to merge it in main and release? :)

**Comment by pawelad** [comment]
Haha, yeah, I've been meaning to give some love to some of my open source projects, this being one of them : )

I think I did about 90% of what I wanted to do, with the main thing left being documentation.... and then other things got in a way. I've been meaning to go back to this since and do a proper release, but haven't found the time yet.

The `dev` branch should be in a good state, feel free to give it a go (https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/) and I'll try my best to finish the remaining 10% and release it soon.

**Comment by pawelad** [comment]
Hey - it’s been a while, but in case you’re sill interested, I _just_ released v1.0.0. Just note that it's almost a complete rewrite and has a different API from v0.11.0
